# Generated by Django 5.2.6 on 2025-10-29 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['track', 'user'], name='music_revie_track_i_744f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['artist', 'title'], name='music_track_artist__7f26ba_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['genre'], name='music_track_genre_i_8a7514_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('track', 'user'), name='uniq_review_per_user_track'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_between_1_and_5'),
        ),
    ]
