# Generated by Django 5.2.6 on 2025-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_track_options_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='average_rating_cached',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='reviews_count_cached',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
