# Generated by Django 5.2.6 on 2025-10-29 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_track_average_rating_cached_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='rating_between_1_and_5',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='atmosphere_vibe',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='individuality',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rhyme_imagery',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='structure_rhythm',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='style_execution',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='trend_relevance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rhyme_imagery__gte', 0), ('rhyme_imagery__lte', 10)), name='ri_0_10'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('structure_rhythm__gte', 0), ('structure_rhythm__lte', 10)), name='sr_0_10'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('style_execution__gte', 0), ('style_execution__lte', 10)), name='se_0_10'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('individuality__gte', 0), ('individuality__lte', 10)), name='ind_0_10'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('atmosphere_vibe__gte', 0), ('atmosphere_vibe__lte', 10)), name='av_0_10'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('trend_relevance__gte', 0), ('trend_relevance__lte', 10)), name='tr_0_10'),
        ),
    ]
