# Generated by Django 5.2.6 on 2025-10-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_review_rating_between_1_and_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
