# Generated by Django 5.2.6 on 2025-10-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='authored_date',
            field=models.DateField(blank=True, db_index=True, help_text='Data stworzenia / wydania utworu przez autora.', null=True, verbose_name='Data utworu (autora)'),
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.DurationField(blank=True, help_text='Format: hh:mm:ss lub mm:ss', null=True, verbose_name='Czas trwania'),
        ),
    ]
