# Generated by Django 5.2 on 2025-10-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_track_authored_date_track_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL зображення обкладинки з Cover Art Archive', max_length=500, null=True, verbose_name='Обкладинка треку'),
        ),
    ]
