# Generated by Django 5.2.6 on 2025-11-08 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='playlist_covers/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='music.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_playlists', to='music.track')),
            ],
            options={
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='playlists', through='music.PlaylistTrack', to='music.track'),
        ),
        migrations.AddIndex(
            model_name='playlisttrack',
            index=models.Index(fields=['playlist', 'position'], name='music_playl_playlis_407db8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('playlist', 'track')},
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'is_favorite'], name='music_playl_user_id_996e97_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_favorite', True)), fields=('user',), name='unique_favorite_playlist_per_user'),
        ),
    ]
