# Generated by Django 5.2.6 on 2025-11-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_playlist_playlisttrack_playlist_tracks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
