# Generated by Django 5.2.6 on 2025-11-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_playlist_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_event_playlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL of the cover image from Cover Art Archive', max_length=500, null=True, verbose_name='Track cover'),
        ),
    ]
