# Generated by Django 5.2.6 on 2025-11-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Data i godzina zakończenia', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(help_text='Data i godzina rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Dokładne miejsce (np. nazwa klubu, ulica)', max_length=200),
        ),
    ]
