# Generated by Django 5.2.6 on 2025-11-16 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_type', models.CharField(choices=[('time', 'Zmiana czasu'), ('location', 'Zmiana miejsca'), ('date', 'Zmiana daty'), ('other', 'Inne')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('proposed_date', models.DateTimeField(blank=True, help_text='Proponowana nowa data rozpoczęcia', null=True)),
                ('proposed_end_date', models.DateTimeField(blank=True, help_text='Proponowana nowa data zakończenia', null=True)),
                ('proposed_location', models.CharField(blank=True, help_text='Proponowane nowe miejsce', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closes_at', models.DateTimeField(help_text='Kiedy głosowanie się kończy')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(help_text='True = Za, False = Przeciw')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.eventpoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('poll', 'user')},
            },
        ),
    ]
