# Generated by Django 5.2.6 on 2025-11-17 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventpoll_pollvote'),
        ('music', '0012_playlist_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='music.playlist'),
        ),
    ]
