# Generated by Django 5.2.6 on 2025-11-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_bio_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
