# Generated by Django 5.2.6 on 2025-11-06 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_user_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        #migrations.AddConstraint(
        #    model_name='user',
        #    constraint=models.CheckConstraint(condition=models.Q(('xp__gte', 0)), name='users_user_xp_check'),
        #),
    ]
