# Generated by Django 5.2.6 on 2025-11-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_xp_user_users_user_xp_check'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='users_user_xp_check',
        ),
    ]
