# Generated by Django 5.2.6 on 2025-11-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_errorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='content_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='content_type',
            field=models.CharField(choices=[('general', 'Ogólny problem'), ('review', 'Nieodpowiednia recenzja'), ('profile', 'Nieodpowiedni profil'), ('playlist', 'Nieodpowiednia playlista'), ('track', 'Nieodpowiedni utwór')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='report_reason',
            field=models.CharField(blank=True, choices=[('spam', 'Spam'), ('inappropriate', 'Treść nieodpowiednia'), ('harassment', 'Molestowanie/Nękanie'), ('hate_speech', 'Mowa nienawiści'), ('fake', 'Fałszywe informacje'), ('copyright', 'Naruszenie praw autorskich'), ('violence', 'Treści przemocy'), ('other', 'Inne')], max_length=50),
        ),
    ]
